name: secret
on: push
jobs:
  secret:
    runs-on: ubuntu-latest
    name: "Printing secret"
    steps:
      - name: Print secret
        uses: aws-actions/configure-aws-credentials@v1
        with:
          my-secrete:${{secrets.MY_SECRET}}
      
      
